name: Unit Test

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'V*'
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        sudo apt install -y xvfb
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo apt install -y ./wkhtmltox_0.12.6-1.bionic_amd64.deb
        pip install six coverage codecov nose

    - name: Run unit test
      run: nosetests --with-coverage --cover-package=src/imgkit --where tests imgkit_test.py

    - name: Run code coverage
      run: codecov
